name: Publish Package
on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm ci
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        # Publish to npm registry
        - uses: actions/setup-node@v1
          with:
              node-version: 12
              registry-url: https://registry.npmjs.org/
              scope: '@comeon'
        - run: npm publish --access public

          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
